### ISSUE TITLE
LibStub error?

### ISSUE THREAD

**Issue by moonwitch** [p3lim-wow/Backpack#2]
Adrian,

On both Github (which is a whole lot of fun) and WoWi/Curse versions, I am getting LibStub errors (Error loading), I do notice that the slashes in the path are wrong, build issue from GH to packager?

**Comment by p3lim** [comment]
The version on CurseForge/WoWInterface hasn't been updated in a year, and I've been working on a rewrite here on GitHub.
Those loading errors are new to 8.0 and only show because you're missing the embedded libraries. The type of slashes used (/ or \\) is irrelevant, both work.

Regardless, Backpack (or rather LibContainer) is not ready yet, it still has some bugs that prevents it from being released.

**Comment by moonwitch** [comment]
I figured. Submitted it just for other users. I may even try working with it a little. Love the way you write code btw
